on: [push, pull_request]

jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: Target README.md
    steps:
      - name: Github Action Contributor
        uses: 8bithemant/Thank-Action@v.03.02
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
