on: [push, pull_request]

jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: Target README.md
    steps:
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
